language: c
sudo: required
branches:
  only:
    - develop
    - zfs-0.7-release
    - /^\d+\.\d+(\.\d+)?(-\S*)?$/
    - /^v\d+\.\d+(\.\S*)?$/
env:
  global:
    # Travis limits maximum log size, we have to cut tests output
    - CODECOV_TOKEN="987cf0f1-ae3b-477e-b645-954e682f99ec"
    - ZFS_TEST_TRAVIS_LOG_MAX_LENGTH=800

jobs:
  include:
    - os: linux
      arch: amd64
      env:
        - ZFS_BUILD_TAGS=1
        - RUN_UZFS_TESTS=1
        - RUN_ZTESTS=0
        - RELEASE_TAG_DOWNSTREAM=1
    - os: linux
      arch: amd64
      env:
        - ZFS_BUILD_TAGS=0
        - RUN_UZFS_TESTS=0
        - RUN_ZTESTS=1
        - RELEASE_TAG_DOWNSTREAM=0
    - os: linux
      arch: arm64
      env:
        - ZFS_BUILD_TAGS=1
        - RUN_UZFS_TESTS=0
        - RUN_ZTESTS=0
        - RELEASE_TAG_DOWNSTREAM=0

before_install:
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-get update -qq
    - sudo apt-get install --yes -qq gcc-6 g++-6
    - sudo apt-get install --yes -qq build-essential autoconf libtool gawk alien fakeroot libaio-dev
    # linux-header package name is different on arm. 
    - if [ "$TRAVIS_CPU_ARCH" == "arm64" ]; then
        sudo apt-get install --yes -qq linux-headers-generic;
      else
        sudo apt-get install --yes -qq linux-headers-$(uname -r);
      fi
    - sudo apt-get install --yes -qq zlib1g-dev uuid-dev libattr1-dev libblkid-dev libselinux-dev libudev-dev libssl-dev libjson-c-dev
    - sudo apt-get install --yes -qq lcov libjemalloc-dev
    # packages for tests - only on amd64
    - if [ "$TRAVIS_CPU_ARCH" == "amd64" ]; then
        sudo apt-get install --yes -qq parted lsscsi ksh attr acl nfs-kernel-server fio;
      fi
    - sudo apt-get install --yes -qq libgtest-dev cmake
    # packages for debugging
    - sudo apt-get install gdb
    # use gcc-6 by default
    - sudo unlink /usr/bin/gcc && sudo ln -s /usr/bin/gcc-6 /usr/bin/gcc
    - sudo unlink /usr/bin/g++ && sudo ln -s /usr/bin/g++-6 /usr/bin/g++
install:
    # zrepl will make use of /var/tmp/sock directory to create a sock file.
    - mkdir -p /var/tmp/sock
    - pushd .
    - cd /usr/src/gtest
    - sudo cmake CMakeLists.txt
    - sudo make -j4
    - sudo cp *.a /usr/lib
    - popd
    # save the current location to get back
    - pushd .
    - cd ..
    # we need fio repo to build zfs replica fio engine
    - git clone https://github.com/axboe/fio
    - cd fio
    - git checkout fio-3.7
    - ./configure
    - make -j4
    - cd ..
    - git clone https://github.com/openebs/spl
    - cd spl
    - git checkout spl-0.7.9
    - sh autogen.sh
    - ./configure
    - if [ $ZFS_BUILD_TAGS = 1 ]; then
        make -j4;
      else
        make --no-print-directory -s pkg-utils pkg-kmod;
        sudo dpkg -i *.deb;
      fi
    - cd ..
    # Build libcstor for uzfs feature
    - git clone https://github.com/openebs/libcstor.git
    - cd libcstor
    - if [ ${TRAVIS_BRANCH} == "develop" ]; then git checkout master; else git checkout ${TRAVIS_BRANCH} || git checkout master; fi
    - sh autogen.sh;
    - ./configure --enable-debug --with-zfs-headers=$PWD/../cstor/include --with-spl-headers=$PWD/../cstor/lib/libspl/include
    - make -j4;
    - sudo make install;
    - sudo ldconfig
    # return to cstor code
    - popd
    - sh autogen.sh
    - if [ $ZFS_BUILD_TAGS = 1 ]; then
        ./configure --with-config=user --enable-debug --enable-uzfs=yes --with-jemalloc --with-fio=$PWD/../fio --with-libcstor=$PWD/../libcstor/include || travis_terminate 1;
        make -j4;
      else
        ./configure  --enable-debug || travis_terminate 1;
        make --no-print-directory -s pkg-utils pkg-kmod || travis_terminate 1;
        sudo dpkg -i *.deb || travis_terminate 1;
      fi
before_script:
    - make cstyle;
script:
    # run ztest and test supported zio backends
    - if [ $RUN_UZFS_TESTS = 1 ]; then
        export FIO_SRCDIR=$PWD/../fio;
        sudo bash ./print_debug_info.sh &
        sudo bash ../libcstor/tests/cstor/script/test_uzfs.sh -T all || travis_terminate 1;
      fi
    - if [ $RUN_ZTESTS = 1 ]; then
        sudo /sbin/modprobe zfs;
        travis_wait 10 /sbin/ztest || travis_terminate 1;
      fi
    - if [ $ZFS_BUILD_TAGS = 1 ]; then
        ./build_image.sh || travis_terminate 1;
      fi
    # If this build is running due to travis release tag, and
    # this job indicates to push the release downstream, then
    # go ahead and tag the dependent repo.
    # Note that ZFS_BUILD_TAGs is enabled for `arm` and `amd`, 
    # but, release on downstream repository is triggered 
    # after `amd` images have been created. This is controlled
    # by ENV RELEASE_TAG_DOWNSTREAM.
    #
    # $TRAVIS_BRANCH contains the same value as $TRAVIS_TAG.
    # Example: 1.9.0-RC1 tag and 1.9.0-RC1 branch. 
    # OpenEBS release are done from branches named as v1.9.x. 
    # Convert the TRAVIS_TAG to the corresponding release branch.
    - if [ ! -z $TRAVIS_TAG ] && [ $RELEASE_TAG_DOWNSTREAM = 1 ] && [ "$TRAVIS_REPO_SLUG" == "openebs/cstor" ]; then
        REL_BRANCH=$(echo v$(echo "$TRAVIS_TAG" | cut -d'-' -f1 | rev | cut -d'.' -f2- | rev).x) ;
        ./buildscripts/git-release "openebs/istgt" "$TRAVIS_TAG" "$REL_BRANCH" || travis_terminate 1;
      fi
after_failure:
    - find /var/tmp/test_results/current/log -type f -name '*' -printf "%f\n" -exec cut -c -$ZFS_TEST_TRAVIS_LOG_MAX_LENGTH {} \;
after_success:
    - find /var/tmp/test_results/current/log -type f -name '*' -printf "%f\n" -exec cut -c -$ZFS_TEST_TRAVIS_LOG_MAX_LENGTH {} \;
