name: build

on: ['push']

jobs:

  cstor:
    runs-on: ubuntu-16.04
    strategy:
      fail-fast: true
      matrix:
        uzfs_build: [1]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Branch
        run: |
          BRANCH="${GITHUB_REF##*/}"
          REPO_ORG=${{ github.repository_owner }}
          echo "BRANCH=${BRANCH}" >> $GITHUB_ENV
          echo "REPO_ORG=${REPO_ORG}" >> $GITHUB_ENV

      - name: Install Tool dependencies
        run: buildscripts/install-tool-dep.sh

      - name: Install Build dependencies
        run: UZFS_BUILD=${{ matrix.uzfs_build }} buildscripts/install-build-dep.sh

      - name: Check style
        run: make cstyle

      - name: Run Tests
        # run ztest and test supported zio backends
        run: |
          if [ "${{ matrix.uzfs_build }}" = 1 ]; then
            export FIO_SRCDIR=$PWD/../fio
            sudo bash ./print_debug_info.sh &
            sudo bash ../libcstor/tests/cstor/script/test_uzfs.sh -T all || exit 1
          else
            sudo /sbin/modprobe zfs
            /sbin/ztest || exit 1
          fi

      - name: Print Logs
        if: ${{ success() || failure() }}
        run: |
          LOG_FILE="/var/tmp/test_results/current/log"
          if [ -f "${LOG_FILE}" ]; then
            find /var/tmp/test_results/current/log -type f -name '*' -printf "%f\n"
          else
            echo "Log file: ${LOG_FILE} not found"
          fi